config/routes.rb
Rails.application.routes.draw do

  resources :bookmarks

  # get '/bookmarks', to: 'bookmarks#index'
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base

  validates :url, :format => URI::regexp(%w(http https))
  validates :url, presence: true
  validates :url, uniqueness: true
  validates :title, presence: true
  validates :category, :inclusion => { :in => %w(Serious Funny Useful), message: "Category must be Serious, Funny, or Useful" }
end

app/models/concerns/bookmark.rb
class Bookmark < ActiveRecord::Base

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    @bookmarks = Bookmark.all.order(:title)
    # has_favorite = bookmark.is_favorite
    # has_comment = bookmark.comment.present
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end


  def create
    @bookmark = Bookmark.new(bookmark_params)
    if @bookmark.save
      redirect_to bookmarks_path
    else
      render :new
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def update
    @bookmark = Bookmark.find(params[:id])
    if @bookmark.update(bookmark_params)
      redirect_to @bookmark, notice: "You have updated the #{@bookmark.title}"
    else
      render :edit
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark, notice: "You have deleted the bookmark"
  end

  private
  # Define which parameters are allowed to be used to create a bookmark
  def bookmark_params
    params.require(:bookmark).permit([:title, :url, :category, :comment])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def favorited
    if @bookmark.is_favorite
      print "Favorite"
    end
  end

  def commented
    if @bookmark.comment
      print "Comment"
    end
  end
end

app/views/bookmarks/_bookmark.html.erb
<br>
<%= link_to(bookmark.title, bookmark_path(bookmark.id)) %>

|<%= bookmark.category %>

|<%= "Favorite" unless bookmark.is_favorite == false  %>

|<%= "Comment" unless not bookmark.comment.present? %>

| <%= link_to('Edit', edit_bookmark_path(bookmark)) %>
| <%= link_to 'Delete', bookmark, method: :delete, data: {confirm: 'Are you sure?'} %>

app/views/bookmarks/_form.html.erb
<% if @bookmark.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@bookmark.errors.count, "error") %> prohibited this post from being saved:</h2>
<ul>
<% @bookmark.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>

<%= form_for bookmark do |f| %>
    <%= f.label :url %> <br>
    <%= f.text_field :url %>
    <br>
    <%= f.label :title %> <br>
    <%= f.text_area :title %>
    <br>
    <%= f.label :category %> <br>
    <%= f.text_field :category %>
    <br>
    <%= f.label :comment %> <br>
    <%= f.text_field :comment %>
    <br>
    <%= f.submit %>
  <% end %>

app/views/bookmarks/edit.html.erb
<%= render 'form', bookmark: @bookmark %>

app/views/bookmarks/index.html.erb
<h3>Bookmarks</h3>

<%= render partial: "bookmark", collection: @bookmarks %>
<br>
<br>
<%= link_to 'Add a new bookmark', new_bookmark_path %>

app/views/bookmarks/new.html.erb
<%= render 'form', bookmark: @bookmark %>

app/views/bookmarks/show.html.erb
<p>
<%= link_to 'Back to Index', bookmarks_path(@bookmark) %>
<br>
<%= @bookmark.title %>
<br>
<a href="<%= @bookmark.url %>" target="_blank"> <%= @bookmark.url %> </a>
<br>
Comment: <%= @bookmark.comment %>
<br>
<%= "Favorite" unless @bookmark.is_favorite == false  %>
<br>
<%= link_to 'Update', edit_bookmark_path(@bookmark) %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wdi4RailsHwBookmarks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
4
<div class="row">
<div class="col-md-2">
Kickstarter mustache Austin, Williamsburg kogi Helvetica kale chips ennui Truffaut. Asymmetrical bespoke chillwave fingerstache mumblecore, American Apparel authentic seitan farm-to-table yr. Deep v plaid polaroid Schlitz. Squid paleo farm-to-table, fanny pack tote bag cardigan fingerstache YOLO chia. Synth PBR selvage fanny pack bespoke keytar, butcher fap lomo. Pinterest raw denim skateboard, aesthetic jean shorts Blue Bottle sriracha butcher. Swag Austin bespoke flexitarian High Life gastropub.

McSweeney's lo-fi aesthetic, banjo Blue Bottle sustainable Carles Banksy wolf plaid PBR&B leggings. Selfies cliche authentic master cleanse, pour-over flexitarian YOLO Blue Bottle gastropub 3 wolf moon Portland swag drinking vinegar hoodie skateboard. Letterpress roof party shabby chic readymade, tote bag meh Kickstarter fashion axe retro PBR. Direct trade ethical Echo Park trust fund, four loko umami actually street art. Truffaut 8-bit drinking vinegar aesthetic, yr polaroid Neutra flexitarian retro Cosby sweater. Fixie pickled High Life tote bag Truffaut typewriter YOLO. Wolf 3 wolf moon American Apparel viral meggings wayfarers, farm-to-table flannel ethical Bushwick.

Bespoke XOXO squid, Neutra Austin ugh lo-fi Marfa. Pug keytar mixtape leggings, hoodie pour-over distillery tousled polaroid. Mlkshk chambray meh, bitters Neutra drinking vinegar forage Brooklyn whatever pork belly. Beard plaid flexitarian retro, pour-over letterpress wayfarers ugh Pitchfork small batch Brooklyn single-origin coffee. Plaid 8-bit blog ugh, organic food truck keytar cornhole typewriter selfies. Kale chips polaroid ennui, Austin PBR brunch flannel hashtag Marfa lo-fi freegan. Roof party bicycle rights Echo Park banh mi, brunch pour-over Bushwick sartorial.

Polaroid four loko deep v jean shorts irony. Ethical deep v cornhole irony. Flannel leggings mumblecore, stumptown crucifix YOLO slow-carb plaid put a bird on it Neutra synth master cleanse. Tattooed hashtag mlkshk gastropub, Intelligentsia synth Portland. Cardigan Blue Bottle ugh Pinterest meh. Kogi semiotics Bushwick Thundercats retro church-key. Blue Bottle chia beard, paleo YOLO art party kogi banjo.
</div>
<div class="col-md-10"> <%= yield %> </div>
</div>
</div>
</body>
</html>